export const LOAD_PRODUCTS_REQUEST = "LOAD_PRODUCTS_REQUEST";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const SET_CARTLIST = "SET_CARTLIST";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const OPEN_MODAL_CART = "OPEN_MODAL_CART";
export const TOGGLE_FAVORITE = "TOGGLE_FAVORITE";
